version: 2.1
# Use a package of configuration called an orb.
jobs:
  #create_infrastructure: 
  #  docker:
  #    - image: amazon/aws-cli
  #  steps:
  #    - checkout
  #    - run:
  #        name: Create Cloudformation Stack
  #        command: |
  #          aws cloudformation deploy \
  #            --template-file template.yml \
  #            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #            --region us-east-1
  #upload_files:
  #  docker:
  #    - image: circleci/node:13.8.0
  #  steps:
  #    - persist_to_workspace:
  #      root: ~/
  #      paths:
  #        - "*"
  configure_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: 
            - "11:3c:d9:9c:46:0c:58:02:f9:09:0b:b9:89:21:68:1c" 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: add ssh
          command: |
            ssh ubuntu@ec2-52-54-216-236.compute-1.amazonaws.com
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml -vvv

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - configure_infrastructure